language: python
python:
  - "3.6"
# command to install dependencies
cache:
  directories:
    - node_modules

env:
  global:
    PROPERLY_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

install:
  - ./setup.sh

jobs:
  include:
    - stage: test
      script: ./test.sh
    - stage: deploy
      if: branch == master
      script: ./deploy_ci.sh
